/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RunnerController_list"];
        put?: never;
        post: operations["RunnerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RunnerController_detail"];
        put?: never;
        post?: never;
        delete: operations["RunnerController_remove"];
        options?: never;
        head?: never;
        patch: operations["RunnerController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterDto: {
            /** Format: email */
            email: string;
            displayName: string;
            password: string;
            /**
             * @default RUNNER
             * @enum {string}
             */
            category: "RUNNER" | "CYCLIST" | "WALKER";
            /**
             * @default USER
             * @enum {string}
             */
            role: "ADMIN" | "USER";
        };
        AuthUserDto: {
            id?: string;
            email?: string;
            displayName?: string;
            photoUrl?: string;
            /** @enum {string} */
            category?: "RUNNER" | "CYCLIST" | "WALKER";
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        ListUsersQueryDto: {
            /**
             * @description ユーザーの役割でフィルタリング（ADMIN | USER）
             * @example USER
             * @enum {string}
             */
            role?: "ADMIN" | "USER";
            /**
             * @description ユーザーのカテゴリでフィルタリング（RUNNER | CYCLIST | WALKER）
             * @example RUNNER
             * @enum {string}
             */
            category?: "RUNNER" | "CYCLIST" | "WALKER";
        };
        PublicUserDto: {
            /** @description ユーザーID */
            id: string;
            /** @description メールアドレス */
            email: string;
            /** @description 表示名 */
            displayName: string;
            /** @description プロフィール画像URL */
            photoUrl?: string;
            /**
             * @description ユーザーの役割（ADMIN | USER）
             * @enum {string}
             */
            role: "ADMIN" | "USER";
            /**
             * @description ユーザーのカテゴリ（RUNNER | CYCLIST | WALKER）
             * @enum {string}
             */
            category: "RUNNER" | "CYCLIST" | "WALKER";
            /** @description アクティブかどうか */
            isActive: boolean;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        UpdateUserDto: {
            id?: string;
            email?: string;
            displayName?: string;
            photoUrl?: string;
            /** @enum {string} */
            category?: "RUNNER" | "CYCLIST" | "WALKER";
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        CreateRunnerDto: {
            displayName: string;
            bio?: string;
            area?: string;
            paceSec?: number;
            tags?: string[];
            avatarUrl?: string;
            isPublic?: boolean;
        };
        UpdateRunnerDto: {
            displayName?: string;
            bio?: string;
            area?: string;
            paceSec?: number;
            tags?: string[];
            avatarUrl?: string;
            isPublic?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    UsersController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 現在ログイン中のユーザー情報を取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"];
                };
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description プロフィール更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"];
                };
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: {
                /** @description ユーザーの役割でフィルタリング（ADMIN | USER） */
                role?: "ADMIN" | "USER";
                /** @description ユーザーのカテゴリでフィルタリング（RUNNER | CYCLIST | WALKER） */
                category?: "RUNNER" | "CYCLIST" | "WALKER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー一覧取得（role、categoryでフィルタリング可能） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"][];
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 特定ユーザー情報取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"];
                };
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー削除（将来的に管理者権限必要） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunnerController_list: {
        parameters: {
            query: {
                page: string;
                limit: string;
                area: string;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunnerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunnerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunnerController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunnerController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunnerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRunnerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
